### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by random-robbie** [s3c-krd/s3cXSSer#21]
Hey,

Nice plugin!

it could do with an easy on and off switch as it's triggering when it's not wanted and only seems to be turned off by disabling it at the moment.

**Comment by random-robbie** [comment]
![Screenshot 2022-10-24 at 14 34 15](https://user-images.githubusercontent.com/4902869/197538764-7e0dca7c-16ea-4aa6-9647-9234e576841f.png)
i also seem to get this a lot of the time.

**Comment by s3c-krd** [comment]
Hey random-robbie!, thank you for your feedback,

when the popup shows no results that means there is no parameters on this page,thanks

**Comment by random-robbie** [comment]
i am seeing this box before the whole page loads correctly. 
any way to ensure the page is loaded before the plugin scans?

**Comment by s3c-krd** [comment]
This extension will not scan pages/(documents) which load with JavaScript code in my plan add it in the feature

**Comment by rudSarkar** [comment]
So like it's just use the GET and POST parameter to perform the scan?

**Comment by s3c-krd** [comment]
> i am seeing this box before the whole page loads correctly.
> any way to ensure the page is loaded before the plugin scans?

Yes , there’s a event listener once the page completely loaded then it will check

**Comment by s3c-krd** [comment]
> So like it's just use the GET and POST parameter to perform the scan?

It will get all hidden and visible parameters from the page and will check it all
